spring.datasource.url=jdbc:postgresql://localhost:5432/Blog_Test
spring.datasource.username=postgres
spring.datasource.password=eve@123
spring.datasource.driver-class-name=org.postgresql.Driver

# This will create table automatically in your database
#spring.jpa.hibernate.ddl-auto=create
